name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Setup Node.js 🔧
          uses: actions/setup-node@v3
          with:
            node-version: '18'
            cache: 'yarn'
        
        - name: Install and build site 🔧
          run: |
            yarn install --frozen-lockfile
            yarn run build
        
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
          
        - name: Deploy site 🚀
          id: static_web_app_build_and_deploy
          uses: Azure/static-web-apps-deploy@v1
          with:
            azure_static_web_apps_api_token: ${{ steps.static_web_app_apikey.outputs.APIKEY }}
            repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
            action: 'upload'
            skip_app_build: true
            #app_location: '/blog-website/build' # App source code path
            # output_location: 'build' # Built app content directory - optional
        
            # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
            #api_location: '' # Api source code path - optional    
        
